# Path to your dotfiles & oh-my-zsh installation.
export DOTFILES=$HOME/.dotfiles
export ZSH=$DOTFILES/oh-my-zsh

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="amuse"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM="$HOME/.dotfiles/oh-my-zsh-custom"

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  history-substring-search
  nvm
)

# Plugin configuration

# Apple chip workaround for nvm plugin in order to find brew nvm in new location
if [[ `uname -m` == 'arm64' ]]; then
  NVM_HOMEBREW="/opt/homebrew/opt/nvm"
fi

# look for .nvmrc files to autoload the correct node version (nvm plugin)
export NVM_AUTOLOAD=1

# untracked local rc file to update values before loading oh-my-zsh
# i.e. if you need to set any variables that affect plugin execution, you have
# to do it in this file (and not in a $ZSH_CUSTOM loaded file)
[ -r $HOME/.zshrc.local ] && source $HOME/.zshrc.local # just for backwards compat
[ -r $HOME/.zshrc.before ] && source $HOME/.zshrc.before

source $ZSH/oh-my-zsh.sh

# https://github.com/sindresorhus/pure#getting-started
# autoload -U promptinit; promptinit
# prompt pure

# untracked local rc file to update/add values after loading oh-my-zsh
[ -r $HOME/.zshrc.after ] && source $HOME/.zshrc.after

for file in $DOTFILES/functions/*; do
  source "$file"
done
