#!/bin/bash

# bash_profile

# set 256 color profile where possible
if [[ $COLORTERM == gnome-* && $TERM == xterm ]] && infocmp gnome-256color >/dev/null 2>&1; then
  export TERM=gnome-256color
elif infocmp xterm-256color >/dev/null 2>&1; then
  export TERM=xterm-256color
fi

export BREW_PREFIX=$(brew --prefix)

# Up-front dotfiles configuration
# Not part of `load_dotfiles` because it must be sourced before anything else
# to be sure that commands like `brew` (when installed in a custom location)
# are already added to the PATH.
[ -r $HOME/.dotfilesrc ] && source $HOME/.dotfilesrc;

load_dotfiles() {
  declare -a files=(
    $HOME/.dotfiles/shell/bash_options # Options
    $HOME/.dotfiles/shell/bash_exports # Exports
    $HOME/.dotfiles/shell/bash_aliases # Aliases
    $HOME/.dotfiles/shell/functions/* # Functions
    $HOME/.dotfiles/shell/bash_prompt # Custom bash prompt
    $HOME/.dotfiles/shell/bash_paths # Path modifications
    $BREW_PREFIX/etc/bash_completion # Bash completion (installed via Homebrew)
    $HOME/.bash_profile.local # Local and private settings not under version control (e.g. git credentials)
  )

  # if these files are readable, source them
  for index in ${!files[*]}
  do
    if [[ -r ${files[$index]} ]]; then
      source ${files[$index]}
    fi
  done
}

# initialize environment
init_env() {
  # init rbenv installed via brew
  if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

  # load nvm which is installed via brew
  export NVM_DIR="$HOME/.nvm"
  # Use --no-use flag to load nvm quicker
  # https://github.com/creationix/nvm/issues/539#issuecomment-245791291
  [ -s "$BREW_PREFIX/opt/nvm/nvm.sh" ] && . "$BREW_PREFIX/opt/nvm/nvm.sh" --no-use
}

load_dotfiles
init_env
unset load_dotfiles init_env
