#!/bin/bash

# bash_profile

# set 256 color profile where possible
if [[ $COLORTERM == gnome-* && $TERM == xterm ]] && infocmp gnome-256color >/dev/null 2>&1; then
  export TERM=gnome-256color
elif infocmp xterm-256color >/dev/null 2>&1; then
  export TERM=xterm-256color
fi

# Up-front dotfiles configuration
# Not part of `load_dotfiles` because it must be sourced before anything else
# to be sure that commands like `brew` (when installed in a custom location)
# are already added to the PATH.
[ -r $HOME/.dotfilesrc ] && source $HOME/.dotfilesrc;

load_dotfiles() {
  declare -a files=(
    $HOME/.dotfiles/shell/bash_options # Options
    $HOME/.dotfiles/shell/bash_exports # Exports
    $HOME/.dotfiles/shell/bash_aliases # Aliases
    $HOME/.dotfiles/shell/functions/* # Functions
    $HOME/.dotfiles/shell/bash_prompt # Custom bash prompt
    $HOME/.dotfiles/shell/bash_paths # Path modifications
    $(brew --prefix)/etc/bash_completion # Bash completion (installed via Homebrew)
    $HOME/.bash_profile.local # Local and private settings not under version control (e.g. git credentials)
  )

  # if these files are readable, source them
  for index in ${!files[*]}
  do
    if [[ -r ${files[$index]} ]]; then
      source ${files[$index]}
    fi
  done
}

# initialize rbenv, pyenv and ndenv
init_env() {
  if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
  if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
  if which ndenv > /dev/null; then eval "$(ndenv init -)"; fi
  if pyenv commands | grep -x virtualenv > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi
}

load_dotfiles
init_env
unset load_dotfiles init_env
