#!/bin/bash

# bash_paths

# Directories to be prepended to PATH
declare -a dirs_to_prepend=(
  "/usr/local/bin" # Ensure that this bin always takes precedence over `/usr/bin`
  "/usr/local/sbin" # Mountain Lion comes with php-fpm pre-installed, to ensure you are using the brew version you need to make sure /usr/local/sbin is before /usr/sbin
  "$(brew list | grep -e ^php[0-9][0-9] | grep -v - | head -n 1)/bin"
)

# Directories to be appended to PATH
declare -a dirs_to_append=(
  "/usr/bin"
  "$HOME/bin"
  "$HOME/.dotfiles/bin"
  "$(brew --prefix coreutils)/libexec/gnubin" # Add brew-installed GNU core utilities bin
  "$(brew --prefix)/share/npm/bin" # Add npm-installed package bin
  "./node_modules/.bin" # add nvm node_modules bin
  "$HOME/.ndenv/bin"
  "$HOME/.composer/vendor/bin"
)

# Prepend directories to PATH
for index in ${!dirs_to_prepend[*]}
do
  if [ -d ${dirs_to_prepend[$index]} ]; then
    # If these directories exist, then prepend them to existing PATH
    PATH="${dirs_to_prepend[$index]}:$PATH"
  fi
done

# Append directories to PATH
for index in ${!dirs_to_append[*]}
do
  if [ -d ${dirs_to_append[$index]} ]; then
    # If these bins exist, then append them to existing PATH
    PATH="$PATH:${dirs_to_append[$index]}"
  fi
done

unset dirs_to_prepend dirs_to_append

export PATH
