#!/usr/bin/env zsh
#
# Create a data URI from a file and copy it to the pasteboard
#
# Authors:
#   Nicolas Gallagher <https://github.com/necolas>
#

datauri() {

  local mimeType=$(file -b --mime-type "$1")
  if [[ $mimeType == text/* ]]; then
    mimeType="${mimeType};charset=utf-8"
  fi
  printf "data:${mimeType};base64,$(openssl base64 -in "$1" | tr -d '\n')" | pbcopy | printf "=> data URI copied to pasteboard.\n"

}
