#!/usr/bin/env zsh
#
# Start an HTTP server from a directory, optionally specifying the language & port
#
# Authors:
#   Nicolas Gallagher <https://github.com/necolas>
#

server() {

  local port="3333"
  open "http://localhost:${port}/"

  npx serve -l $port $@

}
