#!/usr/bin/env zsh
#
# Start an HTTP server from a directory, optionally specifying the language & port
#
# Authors:
#   Nicolas Gallagher <https://github.com/necolas>
#

# server() {

local port="${2:-3333}"
open "http://localhost:${port}/"

if [[ "$1" == "ruby" ]]; then
    ruby -run -ehttpd . -p$port
elif [[ "$1" == "sinatra" ]]; then
    ruby -rsinatra -e'set :public_folder, "."; set :port, $port'
elif [[ "$1" == "php" ]]; then
    php -S localhost:$port
else
    # Set the default Content-Type to `text/plain` instead of `application/octet-stream`
    # And serve everything as UTF-8 (although not technically correct, this doesn’t break anything for binary files)
    python -c $'import SimpleHTTPServer;\nmap = SimpleHTTPServer.SimpleHTTPRequestHandler.extensions_map;\nmap[""] = "text/plain";\nfor key, value in map.items():\n\tmap[key] = value + ";charset=UTF-8";\nSimpleHTTPServer.test();' "$port"
fi

# }
