#!/bin/bash

# Test whether a Homebrew formula is already installed
# $1 - formula name (may include options)
formula_exists() {
  if $(brew list $1 >/dev/null); then
    printf "%s already installed.\n" "$1"
    return 0
  fi

  e_warning "Missing formula: $1"
  return 1
}

brew_tap() {
  if brew tap | grep $1 &> /dev/null
  then
    echo "already tapped - $1"
    false
  else
    e_header "Tapping $1"
    brew tap $1
  fi
}

brew_cask() {
  if brew cask list | grep $1 &> /dev/null
  then
    echo "cask already installed - $1"
    false
  else
    e_header "Cask installing $1"
    brew cask install $1
  fi
}

run_brew() {
  # Check for Homebrew
  if type_exists 'brew'; then
    # Use the latest version of Homebrew
    e_header "Updating Homebrew..."
    brew update
    [[ $? ]] && e_success "Done"

    # Upgrade any already-installed formulae
    e_header "Updating any existing Homebrew formulae..."
    brew upgrade
    [[ $? ]] && e_success "Done"

    # Add necessary brew taps
    e_header "Adding brew taps..."
    local -a desired_taps=(
      'caskroom/cask'
      'homebrew/completions'
      'homebrew/dupes'
      'homebrew/versions'
      'homebrew/homebrew-php'
    )

    for index in ${!desired_taps[*]}
    do
      brew_tap ${desired_taps[$index]}
    done

    # update or install desired formulae
    e_header "Checking status of desired Homebrew formulae..."
    local list_formulae
    local -a missing_formulae

    # ** array items can include options for package **
    local -a desired_formulae=(
      'coreutils' # GNU core utilities (those that come with OS X are outdated)
      'git'
      'ack'
      'bash'
      'bash-completion'
      'brew-cask'
      'mysql'
      'nginx'
      'mongodb'
      'php55'
      'php55-mongo'
      'composer'
      'ffmpeg'
      'graphicsmagick'
      'jpeg'
      'macvim --override-system-vim'
      'rbenv'
      'ruby-build'
      'pyenv'
      'pyenv-virtualenv'
      'optipng'
      'phantomjs'
      'tree'
      'vagrant-completion'
      'wget'
      'wp-cli'
    )

    for index in ${!desired_formulae[*]}
    do
      if ! formula_exists ${desired_formulae[$index]}; then
        # Store the name (and options) of every missing formula
        missing_formulae=("${missing_formulae[@]}" "${desired_formulae[$index]}")
      fi
    done

    if [[ "$missing_formulae" ]]; then
      # Convert the array of missing formula into a list of space-separate strings
      list_formulae=$( printf "%s " "${missing_formulae[@]}" )

      e_header "Installing missing Homebrew formulae..."
      # Install all missing formulae
      brew install $list_formulae

      [[ $? ]] && e_success "Done"
    fi

    # update or install desired brew cask applications
    e_header "Installing brew casks..."
    local -a desired_casks=(
      'alfred'
      'appcleaner'
      'calibre'
      'ccleaner'
      'crashplan'
      'dropbox'
      'evernote'
      'firefox'
      'google-chrome'
      'google-drive'
      'handbrake'
      'hipchat'
      'iterm2'
      'mamp'
      'music-manager'
      'pgadmin3'
      'picasa'
      'rdio'
      'robomongo'
      'sequel-pro'
      'sublime-text'
      'todoist'
      'transmit'
      'utorrent'
      'vagrant'
      'vlc'
      'virtualbox'
    )

    for index in ${!desired_casks[*]}
    do
      brew_cask ${desired_casks[$index]}
    done

    # modify Alfred's scope to include the Caskroom
    brew cask alfred

    # Cleanup brew cask
    e_header "Cleaning brew casks..."
    brew cleanup --outdated
    [[ $? ]] && e_success "Done"

    # use latest rsync rather than out-dated OS X rsync
    # install separately from the main formulae list to fix gh-19
    brew install https://raw.github.com/Homebrew/homebrew-dupes/master/rsync.rb

    # Remove outdated versions from the Cellar
    brew cleanup
  else
    printf "\n"
    e_error "Error: Homebrew not found."
    printf "Aborting...\n"
    exit
  fi
}
