#!/usr/bin/env bash

install_composer() {
  e_header "Installing composer..."

  # Check for composer
  if type 'composer' &> /dev/null; then
    printf "Composer already installed. Upgrading to latest version...\n"
    composer self-update
  else
    curl -sS https://getcomposer.org/installer | php
    mv composer.phar /usr/local/bin/composer
  fi
}
