#!/usr/bin/env bash

install_composer() {
  e_header "Installing composer..."

  # Check for composer
  if type 'composer' &> /dev/null; then
    printf "Composer already installed. Upgrading to latest version...\n"
    composer self-update
  else
    # Use official installation method from https://getcomposer.org/download/
    local install_dir="${BREW_PREFIX}/bin"
    local expected_sig="c8b085408188070d5f52bcfe4ecfbee5f727afa458b2573b8eaaf77b3419b0bf2768dc67c86944da1544f06fa544fd47"

    mkdir -p "${install_dir}"

    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    php -r "if (hash_file('sha384', 'composer-setup.php') === '${expected_sig}') { echo 'Installer verified' . PHP_EOL; } else { echo 'Installer corrupt' . PHP_EOL; unlink('composer-setup.php'); exit(1); }"
    php composer-setup.php --quiet --install-dir="${install_dir}" --filename=composer
    php -r "unlink('composer-setup.php');"

    e_success "Composer installed."
  fi
}
