#!/usr/bin/env bash

run_help() {

cat <<EOT
macOS dotfiles - Chris O'Donnell - http://codfish.io/

Usage: $(basename "$0") [options]

Options:
    -h, --help      Print this help text
    --no-packages   Suppress package updates
    --no-sync       Suppress pulling from the remote repository
    --no-macos      Suppress applying custom macOS system preferences
    --with-apps     Install optional macOS GUI Applications    

Documentation can be found at https://github.com/codfish/dotfiles/

Copyright (c) Chris O'Donnell
Licensed under the MIT license.
EOT

}
