#!/usr/bin/env bash

run_help() {

cat <<EOT
macOS dotfiles - Chris O'Donnell - http://codfish.io/

Usage: $(basename "$0") [options]

Options:
    -h, --help         Print this help text
    --no-packages      Skip package updates
    --no-sync          Skip pulling from the remote repository
    --install-casks    Install optional macOS GUI Applications
    --configure-macos  Configure macOS system preferences

Documentation can be found at https://github.com/codfish/dotfiles/

Copyright (c) Chris O'Donnell
Licensed under the MIT license.
EOT

}
