#!/bin/bash

run_list() {

cat <<EOT

OS X dotfiles - Chris O'Donnell - http://codfish.io/

Additional software to install

  Alfred
  AppCleaner
  CCleaner
  CrashPlan
  Dropbox
  Evernote
  Firefox
  Google Chrome
  Google Drive
  Google Photos
  iTerm2
  Kindle
  Pocket
  Sequel Pro
  Solarized Dark
  Sublime Text
  Todoist
  Virtualbox
  VLC
EOT

}
