#!/bin/bash

run_list() {

cat <<EOT

OS X dotfiles - Chris O'Donnell - http://codfi.sh/

Additional software to install

Browsers:
  Firefox
  Google Chrome

Development:
  iTerm 2
  MAMP
  Robomongo
  Sequal Pro
  Tramsmit
  VirtualBox

Other:
  Alfred
  Airmail
  CrashPlan
  Dropbox
  Evernote
  Google Drive
  Growl
  Pocket
  Rdio
  uTorrent
  VLC
EOT

}
