#!/usr/bin/env zsh

run_list_apps() {

cat <<EOT
macOS dotfiles - Chris O'Donnell - https://www.codfish.dev

Optional software to install

  Dash - https://kapeli.com/dash
  iTerm2 - https://www.iterm2.com/downloads.html
  Postico - https://eggerapps.at/postico/
  Starship Prompt - https://starship.rs/
  Virtualbox - https://www.virtualbox.org/wiki/Downloads
  VLC - http://www.videolan.org/vlc/download-macosx.html
EOT

}
