#!/bin/bash

run_list() {

cat <<EOT

OS X dotfiles - Chris O'Donnell - http://codfi.sh/

Additional software to install

Browsers:
  Firefox
  Google Chrome

Development:
  iTerm 2
  Tramsmit
  VirtualBox
  MAMP

Other:
  Alfred
  Dropbox
  Google Drive
  Rdio
  uTorrent
  VLC
EOT

}
