#!/usr/bin/env zsh

# Use fnm to install latest node version, and install latest npm version too
install_latest_node() {
  if type 'fnm' &> /dev/null; then
    e_header "Installing latest Node.js version..."

    fnm install --lts
    fnm default lts/latest
    fnm use lts/latest

    [[ $? ]] && e_success "Done"
  else
    printf "\n"
    e_error "Error: fnm not found."
    printf "Aborting...\n"
    exit
  fi
}

# `npx` is great for most things, but some things I prefer to have in the global
# scope so I can run them directly without thinking twice.
install_npm_packages() {
  # Check for npm
  if type 'npm' &> /dev/null; then
    e_header "Installing Node.js packages..."

    # Install packages globally
    npm install -g vercel \
      renamer@3 \
      npm-check \
      contentful-cli \
      @google/gemini-cli \
      @anthropic-ai/claude-code \
      @openai/codex \
      turbo \
      corepack \
      pnpm \
      nx

    corepack enable

    [[ $? ]] && e_success "Done"
  else
    printf "\n"
    e_error "Error: npm not found."
    printf "Aborting...\n"
    exit
  fi
}
