#!/bin/bash

update_npm() {
  # Check for npm
  if type_exists 'npm'; then
    e_header "Updating npm to the latest version..."

    npm install npm@latest -g
  else
    printf "\n"
    e_error "Error: npm not found."
    printf "Aborting...\n"
    exit
  fi
}

run_npm() {
  # Check for npm
  if type_exists 'npm'; then
    e_header "Installing Node.js packages..."

    # List of npm packages
    local packages="bower gulp grunt-cli node-sass jshint karma yo uglify-js"

    # Install packages globally and quietly
    npm install $packages --global --quiet

    [[ $? ]] && e_success "Done"
  else
    printf "\n"
    e_error "Error: npm not found."
    printf "Aborting...\n"
    exit
  fi
}
